let state={active:[],history:[],config:{MAX_INSIDE:{Female:1,Male:1},LONG_VISIT_MINUTES:10,VERY_LONG_VISIT_MINUTES:15}};let currentGender=localStorage.getItem('toiletQueueTab')||'Female',requestBusy=false,lastRefresh=0,undoVisitId='',toastTimer=null;const $=id=>document.getElementById(id);
document.addEventListener('DOMContentLoaded',()=>{$('sessionName').value=localStorage.getItem('toiletQueueSession')||'Examination Hall';$('teacherName').value=localStorage.getItem('toiletQueueTeacher')||'';$('sessionName').addEventListener('change',()=>{savePrefs();refresh()});$('teacherName').addEventListener('input',savePrefs);$('pupilName').addEventListener('keydown',e=>{if(e.key==='Enter')addPupil()});switchTab(currentGender);refresh();setInterval(refresh,4000);setInterval(()=>{renderTimers();updateStaleStatus()},1000)});
function apiUrl(){const u=window.APP_CONFIG&&window.APP_CONFIG.API_URL;if(!u||u.includes('PASTE_YOUR'))throw new Error('Add your Apps Script web app URL to config.js first.');return u}
async function api(action,payload={}){const r=await fetch(apiUrl(),{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Request failed.');return d}
function savePrefs(){localStorage.setItem('toiletQueueSession',$('sessionName').value.trim());localStorage.setItem('toiletQueueTeacher',$('teacherName').value.trim())}
function switchTab(g){currentGender=g;localStorage.setItem('toiletQueueTab',g);$('femaleTab').classList.toggle('active',g==='Female');$('maleTab').classList.toggle('active',g==='Male');$('queueHeader').className='queue-banner '+g.toLowerCase();$('queueTitle').textContent=g==='Female'?'🚺 Female Toilet':'🚹 Male Toilet';$('addHeading').textContent='Add to '+g+' queue';render()}
async function refresh(){if(requestBusy)return;const s=$('sessionName').value.trim();if(!s){$('syncStatus').textContent='Enter session';return}try{state=await api('getAppState',{session:s});lastRefresh=Date.now();render();$('syncStatus').textContent='Live · '+formatTime(state.serverTime)}catch(e){handleError(e)}}
async function addPupil(){const p={name:$('pupilName').value.trim(),pupilClass:$('pupilClass').value.trim(),gender:currentGender,addedBy:$('teacherName').value.trim(),session:$('sessionName').value.trim()};if(!p.session)return showToast('Enter a hall or exam session.',true);if(!p.name)return showToast('Enter the pupil name.',true);await mutate(async()=>{await api('addPupil',p);$('pupilName').value='';$('pupilName').focus();showToast('Pupil added.');await refresh()})}
async function sendIn(id){await mutate(async()=>{await api('sendIn',{visitId:id});showToast('Pupil sent in.');await refresh()})}
async function markReturned(id){await mutate(async()=>{await api('markReturned',{visitId:id});undoVisitId=id;showToast('Pupil marked returned.',false,true);await refresh()})}
async function undoReturn(){if(!undoVisitId)return;const id=undoVisitId;undoVisitId='';await mutate(async()=>{await api('restoreInside',{visitId:id});showToast('Return undone.');await refresh()})}
async function removeWaiting(id,name){if(!confirm(`Remove ${name} from the waiting queue?`))return;await mutate(async()=>{await api('removeWaiting',{visitId:id});showToast('Removed from queue.');await refresh()})}
async function clearQueues(){const s=$('sessionName').value.trim();if(!s)return;if(!confirm(`Clear all Waiting and Inside pupils for "${s}"? Returned history will remain.`))return;await mutate(async()=>{await api('clearActiveQueues',{session:s});showToast('Active queue cleared.');await refresh()})}
async function mutate(fn){if(requestBusy)return;requestBusy=true;$('app').classList.add('loading');try{await fn()}catch(e){handleError(e)}finally{requestBusy=false;$('app').classList.remove('loading')}}
function render(){const rows=state.active.filter(x=>x.gender===currentGender),w=rows.filter(x=>x.status==='Waiting').sort((a,b)=>new Date(a.queueAdded)-new Date(b.queueAdded)),i=rows.filter(x=>x.status==='Inside').sort((a,b)=>new Date(a.entered)-new Date(b.entered)),max=(state.config.MAX_INSIDE||{})[currentGender]||1;$('waitingCount').textContent=w.length;$('insideCount').textContent=i.length;$('limitText').textContent='Max inside '+max;$('waitingList').innerHTML=w.length?w.map((p,n)=>waitingCard(p,n,i.length,max)).join(''):'<div class="empty">No pupils waiting</div>';$('insideList').innerHTML=i.length?i.map(insideCard).join(''):'<div class="empty">No pupil inside</div>';$('femaleBadge').textContent=state.active.filter(x=>x.gender==='Female').length;$('maleBadge').textContent=state.active.filter(x=>x.gender==='Male').length;renderHistory()}
function waitingCard(p,n,inside,max){const can=n===0&&inside<max;return `<div class="person-card"><div class="person-name">${esc(p.name)}</div><div class="person-meta">${esc(p.pupilClass||'No class')} · Queue #${n+1} · added ${formatTime(p.queueAdded)}${p.addedBy?' · by '+esc(p.addedBy):''}</div><div class="actions"><button class="action-btn send-btn" ${can?'':'disabled'} onclick="sendIn('${js(p.visitId)}')">Send in</button><button class="action-btn remove-btn" onclick="removeWaiting('${js(p.visitId)}','${js(p.name)}')">Remove</button></div></div>`}
function insideCard(p){const m=minutesSince(p.entered),warn=Number(state.config.LONG_VISIT_MINUTES||10),very=Number(state.config.VERY_LONG_VISIT_MINUTES||15),c=m>=very?'verylong':m>=warn?'long':'';return `<div class="person-card ${c}"><div class="person-name">${esc(p.name)}</div><div class="person-meta">${esc(p.pupilClass||'No class')} · entered ${formatTime(p.entered)}<br><span class="timer" data-entered="${esc(p.entered)}">${duration(m)}</span></div><div class="actions single"><button class="action-btn return-btn" onclick="markReturned('${js(p.visitId)}')">Returned</button></div></div>`}
function renderHistory(){const l=(state.history||[]).filter(x=>x.gender===currentGender).slice(0,8);$('historyList').innerHTML=l.length?l.map(p=>{const m=p.entered&&p.returned?Math.max(0,Math.floor((new Date(p.returned)-new Date(p.entered))/60000)):0;return `<div class="history-item"><strong>${esc(p.name)}</strong> · ${esc(p.pupilClass||'')} · ${duration(m)} · returned ${formatTime(p.returned)}</div>`}).join(''):'<div class="empty">No recent returned pupils</div>'}
function renderTimers(){document.querySelectorAll('[data-entered]').forEach(el=>{const m=minutesSince(el.dataset.entered),card=el.closest('.person-card'),warn=Number(state.config.LONG_VISIT_MINUTES||10),very=Number(state.config.VERY_LONG_VISIT_MINUTES||15);el.textContent=duration(m);card.classList.toggle('long',m>=warn&&m<very);card.classList.toggle('verylong',m>=very)})}
function updateStaleStatus(){if(!lastRefresh)return;if(Date.now()-lastRefresh>12000){$('syncStatus').textContent='Data may be stale';$('syncStatus').classList.add('stale')}else $('syncStatus').classList.remove('stale')}
function showToast(msg,err=false,undo=false){const t=$('toast');t.className='toast'+(err?' error':'');t.innerHTML=undo?`<div class="toast-row"><span>${esc(msg)}</span><button class="undo-btn" onclick="undoReturn()">Undo</button></div>`:esc(msg);t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>{t.style.display='none';if(undo)undoVisitId=''},4500)}
function handleError(e){$('syncStatus').textContent='Sync error';showToast(e&&e.message?e.message:String(e||'Unknown error'),true)}function minutesSince(v){if(!v)return 0;return Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000))}function duration(m){return m<1?'< 1 min':m===1?'1 min':m+' mins'}function formatTime(v){if(!v)return'';const d=new Date(v);return isNaN(d.getTime())?'':d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}function js(v){return String(v??'').replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/\r/g,'').replace(/\n/g,'')}
